### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by arejula27** [UNIZAR-30226-2021-02/Frontend-web#5]
- [x] Plantilla de entrada
- [x] Navegación
- [x] Contactar con servidor
- [x] Guardar token de forma persistente
- [x] Aplicar diseño

**Comment by PabloDominguez00** [comment]
Primera pantalla de login y pantalla de Singup hecha, falta la lógica

**Comment by PabloDominguez00** [comment]
Perdón me he equivocado no volverá a ocurrir (mentira)
